---
- name: Set container detail if standalone setup
  set_fact:
    rabbitmq_container_volumes: "{{ rabbitmq_container_standalone_setup_details.volumes|default([], true) }}"
    rabbitmq_container_ports: "{{ rabbitmq_container_standalone_setup_details.ports|default([], true) }}"
    rabbitmq_container_env: "{{ rabbitmq_container_standalone_setup_details.env|default({}, true) }}"
  when: rabbitmq_setup == "standalone"

- name: Set container detail if cluster setup
  set_fact:
    rabbitmq_container_volumes: "{{ rabbitmq_container_cluster_setup_details.volumes|default([], true) }}"
    rabbitmq_container_ports: "{{ rabbitmq_container_cluster_setup_details.ports|default([], true) }}"
    rabbitmq_container_env: "{{ rabbitmq_container_cluster_setup_details.env|default({}, true) }}"
  when: rabbitmq_setup == "cluster"

- name: Copy docker-compose.yml from template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ rabbitmq_path }}/docker-compose.yml"
    mode: '0644'

- name: Start RabbitMQ using Docker Compose
  community.docker.docker_compose:
    project_src: "{{ rabbitmq_path }}"
    files:
      - docker-compose.yml
    state: present
    recreate: smart

- name: Pause for some seconds to give time to the container to come up
  pause:
    seconds: "{{ rabbitmq_container_pause }}"
  when: rabbitmq_container_pause > 0
